### PR TITLE
Adding Northwoods to list of companies

### PR DESCRIPTION
**Pull request by remingtron**

### CODE REVIEW

**Comment by vipermark7** [comment]
Awesome! I presume you're using Ruby on Rails, or is it some other Ruby stack/library for the back-end?

**Comment by remingtron** [comment]
Yep! We have a Rails backend with a React/Typescript frontend (which we are converting to from AngularJS/Coffeescript).

**Comment by vipermark7** [comment]
Hardcore! Best of luck with the conversion :)

**Comment by vipermark7** [comment]
I'm unsure. Will ask someone to deploy it

**Pull request merged**
